### ISSUE TITLE
CI feed does not exists ⚠

### ISSUE THREAD

**Issue by simix-felipebaltazar** [novotnyllc/MSBuildSdkExtras#214]
The CI feed (azure devops) cannot be found at https://pkgs.dev.azure.com/onovotny/GitBuilds/_packaging/MSBuildSdkExtras/nuget/v3/index.json

![image](https://user-images.githubusercontent.com/42358163/76759011-965b1500-6769-11ea-919b-735641083d99.png)

**Comment by clairernovotny** [comment]
The feed changed and can now be found at `https://pkgs.dev.azure.com/clairernovotny/GitBuilds/_packaging/MSBuildSdkExtras/nuget/v3/index.json`
