### ISSUE TITLE
Per-RuntimeIdentifier packaging doesn't allow overriding build output path in nupkg

### ISSUE THREAD

**Issue by andrew-boyarshin** [novotnyllc/MSBuildSdkExtras#217]
<https://github.com/novotnyllc/MSBuildSdkExtras/blob/4958e227bbd7ab023e2e5ad384f51ae62e3a3a15/Source/MSBuild.Sdk.Extras/Build/RIDs.targets#L165-L167>

This feels too restrictive. ~~I'm not sure I can override this without overriding the whole target (and that requires dropping `Sdk` property from `<Project />` and doing `<Import Sdk="..." />`  manually), or patching another target in `GenerateNuspecDependsOn` with `<None Update="" />`.~~ nevermind, found a simple workaround, see the first comment below.

Proposal: extract path template to a property and allow simpler override.

### Additional notes
The original issue title was `Per-RuntimeIdentifier packaging doesn't respect BuildOutputTargetFolder`, but then the whole property value is different from a traditional path under `/lib` or `/tools`...

It'd be great to have such things (`ItemGroup`s) under some condition (like `'$(ExtrasIncludeDefaultProjectBuildOutputInPack)' != 'false'`), so that when such issues arise it would be ~~possible~~ simpler to ~~hackaround~~ fix it locally by setting property (in my example to `false`) and adding items manually.

Stumbled upon this while working on SharpGen, it provides its own MSBuild tasks, so they should be in `tools` directory for them to be dev-only deps. [ref](https://github.com/SharpGenTools/SharpGenTools/blob/d14e0b47387c230c6e334c5de2016cb2212b2014/SharpGenTools.Sdk/SharpGenTools.Sdk.csproj#L9)

**Comment by andrew-boyarshin** [comment]
My final version of workaround:
```xml


  <PropertyGroup>
    <GenerateNuspecDependsOn>$(GenerateNuspecDependsOn);PatchPackagePath</GenerateNuspecDependsOn>
  </PropertyGroup>

  <Target Name="PatchPackagePath">

    <ItemGroup>
      <_PackageFilesToPatch Include="@(_PackageFiles->WithMetadataValue('BuildAction', 'None')->WithMetadataValue('Pack', 'true')->HasMetadata('TargetFramework')->HasMetadata('Rid'))" />
      <_PackageFilesToPatch Remove="@(_PackageFilesToPatch)" Condition="'%(TargetFramework)' == '' or '%(Rid)' == ''" />
      <_PackageFiles Remove="@(_PackageFilesToPatch)" />
      <_PackageFilesToPatch Update="@(_PackageFilesToPatch)" PackagePath="tools/%(TargetFramework)/%(Rid)" />
      <_PackageFiles Include="@(_PackageFilesToPatch)" />
      <_PackageFilesToPatch Remove="@(_PackageFilesToPatch)" />
    </ItemGroup>

  </Target>
```

**Comment by clairernovotny** [comment]
Is there a PR you'd suggest to make this generic/flexible?

**Comment by andrew-boyarshin** [comment]
@clairernovotny I'll try to think of the most flexible approach to this and make a PR. Can't guarantee I'll do it, though. I'm already on the 5th level of the dependency chain (Project->Framework->Bindings->SharpGen->MSBuild SDK), the dev cycle gets more difficult by the minute.

**Comment by andrew-boyarshin** [comment]
After #218 this can still be improved: modify `Impl` to take some new ItemSpec (abusing the fact that items in MSBuild preserve order), replace placeholders (like `<RID>` -> `%(Rid)`), join into string with `/` separator via `@(..., '/')`. But I believe it's me overthinking, so my PR does much simpler version which still enables full customization.
