### ISSUE TITLE
Wrong inference for net5.0 TFM

### ISSUE THREAD

**Issue by azchohfi** [novotnyllc/MSBuildSdkExtras#232]
Shouldn't this consider `net5.0`?
https://github.com/novotnyllc/MSBuildSdkExtras/blob/792a30d95565c65ec9e790ead13e3c2494507094/Source/MSBuild.Sdk.Extras/Build/Inference.targets#L53-L55

**Comment by clairernovotny** [comment]
Fair point, can you please open an issue to track?

**Comment by azchohfi** [comment]
I'm sorry Claire, where do you want me to do that? I thought here was the right place. I could also rename this issue and add more info.

**Comment by clairernovotny** [comment]
Sorry, you're right, don't mind me, it's been a long day :)

**Comment by chucker** [comment]
I wonder if this (well, the _opposite_ of this?) is why, after I installed .NET 5.0 preview 7, `ExtrasEnableWpfProjectSetup` no longer seemed to work right on a project that's .NET Framework 4.7.2?
