### ISSUE TITLE
Can't find version 3.x

### ISSUE THREAD

**Issue by bddckr** [novotnyllc/MSBuildSdkExtras#246]
Hey there! Thanks a lot for this project and the continued work on it.

The readme states
> Important: 3.x of the Extras requires the .NET 5 SDK or later. The SDK can build previous targets, like netcoreapp3.1. The extras 2.x supports SDK 2.x and 3.x.

But I can only see version 2.1.2 in the nuget.org feed and 2.1.6 in the CI feed.

As I'm getting some warning using the .NET 5 SDK (v5.0.100) I thought I'd try to update.
> 4>C:\Users\bddckr\.nuget\packages\msbuild.sdk.extras\2.1.2\Sdk\Sdk.props(25,3): warning MSB4011: "C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.NET.Sdk.WindowsDesktop.props" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.props (147,3)". This is most likely a build authoring error. This subsequent import will be ignored.

**Comment by xen2** [comment]
Same thing here.
We would like to switch to .NET 5 but couldn't find any branch with this supposed 3.x, maybe it's only a plan so far?

**Comment by clairernovotny** [comment]
Doesn't exist yet.... been busy with a number of other things. The 2.x version does work, just ignore the warnings. 3.x probably won't be out until mid-late December due to other commitments.

**Comment by Axemasta** [comment]
I'm seeing **MSB4011** in one of my libraries aswell as other ones out & about (like the XamarinCommunityToolkit).

```
/Users/alex.duffell/.nuget/packages/msbuild.sdk.extras/2.1.2/Sdk/Sdk.props(25,3) : 
warning MSB4011: "/usr/local/share/dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props" 
cannot be imported again. It was already imported at 
"/usr/local/share/dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.props (147,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
[/Users/alex.duffell/Documents/GitHub/XamarinCommunityToolkit/XamarinCommunityToolkit/Xamarin.CommunityToolkit.csproj]
```

Is there anyway I can suppress these warnings until a new version released? 

I've tried `<NoWarn>MSB4011</NoWarn>` and [`<MSBuildWarningsAsMessages>MSB4011</MSBuildWarningsAsMessages>`](https://github.com/dotnet/msbuild/issues/4038) but no luck so far 😅

**Comment by clairernovotny** [comment]
@dsplaisted @rainersigwald do you know if this error can be suppressed?

**Comment by GeertvanHorrik** [comment]
I tried the NoWarn approach as well :-) . I even tried adding an extra _ExtrasWindowsSdkAlreadyImported (if TargetFramework ends with "windows"), but my real problem was I had to update to NuGet 5.8 which isn't available via `nuget update -self` yet.

**Comment by rainersigwald** [comment]
> do you know if this warning can be suppressed?

Not at the moment: dotnet/msbuild#4038

**Comment by rolfik** [comment]
Version 2 from nuget.org does not work for me with .NET 5 projects, but I can use current one from this repository packaged into custom [nuget](https://github.com/novotnyllc/MSBuildSdkExtras/files/5566757/MSBuild.Sdk.Extras.3.0.0-HaSaM.nupkg.zip).
We still have some warnings but can live with it for now.
There is still one problem we are investigating: https://github.com/NuGet/Home/issues/10289.

**Comment by Daniel-Svensson** [comment]
I've created a PR #249 which should fix the build warning
