### ISSUE TITLE
.NET 5 / C# 9 multi targeting on macOS issue

### ISSUE THREAD

**Issue by mfkl** [novotnyllc/MSBuildSdkExtras#255]
Hi,

Given
```
<Project Sdk="MSBuild.Sdk.Extras">

  <PropertyGroup>

    <TargetFrameworks>net5.0;xamarin.ios10</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

</Project>
```

and 

```
{
    "msbuild-sdks": {
        "MSBuild.Sdk.Extras": "3.0.23"
    },
    "sdk": {
        "version": "5.0.101"
    }
}
```

Invoking `msbuild` gives 

```
CSC : error CS1617: Invalid option '9.0' for /langversion. Use '/langversion:?' to list supported values
(_CheckForUnsupportedNETCoreVersion target) ->
  /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(127,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 5.0.  Either target .NET Core 3.1 or lower, or use a version of the .NET SDK that supports .NET Core 5.0.
```

It builds fine on Windows, interestingly. 
I've made sure it builds fine on macOS with a single target and without MSBuildSdkExtras.

repro: https://github.com/mfkl/test-net5-mac-multitarget

**Comment by clairernovotny** [comment]
Based on the error, it looks like you need a newer version of Mono?

**Comment by mfkl** [comment]
Apologies, you are correct. C# 9 is supported in yesterday's nightly mono build, but not in the current stable / VS version.

**Comment by mfkl** [comment]
Building C# 9 single target works, but with your SDK and multitarget it gives
```
(CoreCompile target) ->
  CSC : error CS1900: Warning level must be in the range 0-4
```
Your SDK is likely not at fault here, just FYI.

**Comment by jmarolf** [comment]
> CSC : error CS1900: Warning level must be in the range 0-4

This error means you are trying to build a net5.0 with an older (pre C# 9) compiler. You can manually specify `<WarningLevel>4</WarningLevel>` to make it go away but some C# 9 features may not work.

**Comment by mfkl** [comment]
`csc -langversion:?` does return a list that includes C# 9. `csc --version` returns 3.7.0-5.20367.1 which should include full C# 9 support. I think this is a bug and I can't think of another place to open an issue as the default SDK with single target builds the same csproj fine.

https://github.com/mfkl/mac-multitarget-net5-cs9

**Comment by mfkl** [comment]
> You can manually specify `<WarningLevel>4</WarningLevel>` in your project file to make it go away

Interestingly, specifying this in the csproj seems to get ignored. Building with `msbuild`.

**Comment by jmarolf** [comment]
@mfkl I can no longer access your repro project. If properties you set in your project file do not get picked up you have a very broken build environment. I do not know if that is due to msbuildsdkextrasm mono, the .NET sdk, or some combination of all three.

If you feel the issue lies with the sdk I would open a new issue [here](https://github.com/dotnet/sdk/issues/new)

If you feel this is an issue with mono's build environment I would open a new issues [here](https://github.com/mono/mono/issues/new)

**Comment by mfkl** [comment]
@jmarolf https://github.com/mfkl/mac-multitarget-net5-cs9. Thanks, will open an issue at mono.

**Comment by jmarolf** [comment]
quick question: do you actually need MSBuildSDKExtras? Does this not work for you?

```
<TargetFrameworks>net5.0;net5.0-ios</TargetFrameworks>
```

**Comment by clairernovotny** [comment]
IOS currently requires the Extras. This is something that .NET 6 should be addressing.

**Comment by jmarolf** [comment]
gotcha, thanks!
