### ISSUE TITLE
Failures with GetDirectoryName

### ISSUE THREAD

**Issue by bstordrup** [novotnyllc/MSBuildSdkExtras#273]
When building on a TeamCity configuration, I sometimes get this error:

The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.

In TeamCity, I use the MSBuild runner, and the MSBuild.exe is found in VS 2017 Community edition.

**Comment by clairernovotny** [comment]
The 3.x of the Extras has only been tested with VS 2019 and up. Please use 2.x on lower versions of VS.
